replicaCount: 1
images:
  ui: dingobar/tellmewhattodo-ui:latest
  backend: dingobar/tellmewhattodo:latest
  rabbitmq: rabbitmq:latest
pvc:
  storageClassName: ~
  storage: 100Mi
service:
  type: NodePort

rabbitmq:
  persistence:
    enabled: false

job:
  config:
    extractors:
      - type: github
        config:
          repository: dingobar/charts
      - type: github
        config:
          repository: apache/airflow
      - type: github
        config:
          repository: jupyterhub/zero-to-jupyterhub-k8s
      - type: github
        config:
          repository: mlflow/mlflow
      - type: github
        config:
          repository: meltano/meltano
