apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tellmewhattodo.fullname" . }}
  labels:
    {{- include "tellmewhattodo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tellmewhattodo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tellmewhattodo.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-ui
          image: {{ .Values.images.ui }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
              name: config
        - name: {{ .Chart.Name }}-backend
          image: {{ .Values.images.backend }}
          imagePullPolicy: IfNotPresent
          env:
            - name: TELLME_DATABASE_LOCATION
              value: /srv/data/database.db
            - name: TELLME_RABBITMQ_HOST
              value: {{ .Release.Name }}-rabbitmq
            - name: TELLME_RABBITMQ_PORT
              value: "5672"
            - name: TELLME_RABBITMQ_USERNAME
              value: user
            - name: TELLME_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-rabbitmq
                  key: rabbitmq-password
            - name: TELLME_EXTRACTOR_JOB_CONFIG_PATH
              value: /srv/config/config.yaml
          volumeMounts:
            - mountPath: /srv/data
              name: data
            - mountPath: /srv/config/config.yaml
              subPath: config.yaml
              name: config
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "tellmewhattodo.fullname" . }}
        - name: config
          configMap:
            name: {{ include "tellmewhattodo.fullname" . }}
