apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tellmewhattodo.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
  storageClassName: {{ .Values.pvc.storageClassName }}
