repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.7.3
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.388
    hooks:
      - id: pyright
  - repo: https://github.com/python-poetry/poetry
    rev: "1.8.4" # add version here
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args:
          - "-f"
          - "requirements.txt"
          - "-o"
          - "requirements.txt"
  - repo: local
    hooks:
      - id: nginx-conf-from-template
        name: "Generate compose nginx config from template"
        entry: API_HOST=tmwtd envsubst < nginx.template.conf > nginx.compose.conf
