repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.3
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.388
    hooks:
      - id: pyright
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: "0.7.12"
    hooks:
      - id: uv-lock
      - id: uv-export
  - repo: local
    hooks:
      - id: set-version
        name: Set versions based on VERSION file
        language: system
        entry: ./scripts/set-version.sh
        files: ^(Chart\.yaml|VERSION|pyproject\.toml)$
