repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.3
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.388
    hooks:
      - id: pyright
  - repo: https://github.com/python-poetry/poetry
    rev: "1.8.4"
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args:
          - --no-update
      - id: poetry-export
        args:
          - "-f"
          - "requirements.txt"
          - "-o"
          - "requirements.txt"
  - repo: local
    hooks:
      - id: set-version
        name: Set versions based on VERSION file
        language: system
        entry: ./scripts/set-version.sh
        files: ^(Chart\.yaml|VERSION|pyproject\.toml)$
