FROM node:22 AS build

WORKDIR /var/app
COPY . .
RUN npm install --include=dev && \
    npm run build

FROM nginx:alpine-slim

COPY --from=build /var/app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
