services:
  tmwtd:
    build: .
    environment:
      - TELLME_RABBITMQ_HOST=rabbitmq
      - TELLME_RABBITMQ_USERNAME=guest
    volumes:
      - ./database.db:/var/app/database.db
    ports:
      - 8000:8000
  tmwtd-ui:
    build:
      dockerfile: Dockerfile.ui
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672:5672
