FROM node:22 AS build

WORKDIR /var/app
COPY . .
ENV VITE_API_URL="./api"
RUN npm install --include=dev && \
    npm run build

FROM nginx:alpine-slim

COPY --from=build /var/app/dist /usr/share/nginx/html
