[tool.poetry]
name = "tellmewhattodo"
version = "3.0.0"
description = "Simple app that checks for what to do and presents that in a website"
authors = ["Martin Morset <mmo@one.com>"]
license = "MIT"
packages = [{ include = "tellmewhattodo" }]

[tool.poetry.dependencies]
python = "^3.11"

pydantic = "^1.9.1"
requests = "^2.28.1"
click = "^8.1.3"
PyYAML = "^6.0"

[tool.poetry.extras]
s3 = ["boto3"]

[tool.poetry.scripts]
tellmewhattodo = 'tellmewhattodo.cli:cli'

[tool.poetry.dev-dependencies]
black = "^22.6.0"
boto3-stubs = { version = "1.24.43", extras = ["s3"] }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tools.black]
line-length = 100