apiVersion: v2
name: tmwtd
description: A Helm chart for TMWTD
type: application
version: 1.0.0
appVersion: "3.0.0"
dependencies:
  - name: rabbitmq
    version: 15.1.0
    repository: oci://registry-1.docker.io/bitnamicharts
