apiVersion: v2
name: tellmewhattodo
description: A Helm chart for TellMeWhatToDo
type: application
version: 7.1.4
appVersion: 7.1.4
dependencies:
  - name: rabbitmq
    version: "^15.1"
    repository: oci://registry-1.docker.io/bitnamicharts
