replicaCount: 1
images:
  ui: dingobar/tellmewhattodo-ui:7.1.2
  backend: dingobar/tellmewhattodo-backend:7.1.1
  job: curlimages/curl:latest
pvc:
  storageClassName: ~
  storage: 100Mi
service:
  type: NodePort
cronjob:
  crontab: "5 4 * * *"

rabbitmq:
  persistence:
    enabled: false

job:
  config:
    extractors:
      - type: github
        config:
          repository: apache/airflow
      - type: github
        config:
          repository: jupyterhub/zero-to-jupyterhub-k8s
      - type: github
        config:
          repository: mlflow/mlflow
      - type: github
        config:
          repository: meltano/meltano
