// This file is auto-generated by @hey-api/openapi-ts

export const AlertSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        extractor_id: {
            type: 'string',
            title: 'Extractor Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        alert_type: {
            '$ref': '#/components/schemas/AlertType'
        },
        acked_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Acked At'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        url: {
            anyOf: [
                {
                    type: 'string',
                    minLength: 1,
                    format: 'uri'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        last_acked_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Acked Name'
        },
        acked: {
            type: 'boolean',
            title: 'Acked',
            readOnly: true
        }
    },
    type: 'object',
    required: ['id', 'extractor_id', 'name', 'created_at', 'alert_type', 'acked'],
    title: 'Alert'
} as const;

export const AlertTypeSchema = {
    type: 'string',
    enum: ['github', 'dockerhub', 'docker_helm'],
    title: 'AlertType'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;