// This file is auto-generated by @hey-api/openapi-ts

export type Alert = {
  id: string
  name: string
  created_at: string
  alert_type: AlertType
  acked: boolean
  description?: string | null
  url?: string | null
}

export type AlertType = 'github'

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type GetAlertsGetResponse = Array<Alert>

export type GetAlertsGetError = unknown

export type AckAlertAlertIdPatchData = {
  path: {
    alert_id: string
  }
  query: {
    acked: boolean
  }
}

export type AckAlertAlertIdPatchResponse = unknown

export type AckAlertAlertIdPatchError = HTTPValidationError
