// This file is auto-generated by @hey-api/openapi-ts

export type Alert = {
    id: string;
    extractor_id: string;
    name: string;
    created_at: string;
    alert_type: AlertType;
    acked_at?: (string | null);
    description?: (string | null);
    url?: (string | null);
    last_acked_name?: (string | null);
    readonly acked: boolean;
};

export type AlertType = 'github' | 'dockerhub' | 'docker_helm';

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type GetAlertsGetData = {
    query?: {
        latest_only?: boolean;
    };
};

export type GetAlertsGetResponse = (Array<Alert>);

export type GetAlertsGetError = (HTTPValidationError);

export type StartAlertsCheckJobPostResponse = (unknown);

export type StartAlertsCheckJobPostError = unknown;

export type AckAlertAlertIdPatchData = {
    path: {
        alert_id: string;
    };
    query: {
        acked: boolean;
    };
};

export type AckAlertAlertIdPatchResponse = (Alert);

export type AckAlertAlertIdPatchError = (HTTPValidationError);
