apiVersion: v1
kind: Service
metadata:
  name: {{ include "tellmewhattodo.fullname" . }}
  labels:
    {{- include "tellmewhattodo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - targetPort: http
      protocol: TCP
      name: http
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- else }}
      port: 80
      {{- end }}
  selector:
    {{- include "tellmewhattodo.selectorLabels" . | nindent 4 }}
