name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        app:
          - image: tellmewhattodo
            dockerfile: Dockerfile
          - image: tellmewhattodo-ui
            dockerfile: Dockerfile.ui
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Read version from file
      id: version
      run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./${{ matrix.app.dockerfile }}
        push: true
        tags: dingobar/${{ matrix.app.image }}:${{ env.VERSION }}
  chart:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4.2.0
        id: install-helm
      - name: Build and push OCI helm chart
        id: helm-build-push
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | helm registry login registry-1.docker.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          ./scripts/build-and-push-chart.sh
